{% set name = "ipytone" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f921cd630bde201ed90eccc140b2e473ee253673b00581f32314a7befdd68ec

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - jupyter-packaging
  run:
    - ipywidgets >=7.6.0
    - python >=3.6

test:
  imports:
    - ipytone
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipytone/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipytone/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/ipytone/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipytone\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipytone\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\ipytone\\package.json (exit 1)          # [win]

about:
  home: https://github.com/benbovy/ipytone
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Interactive audio in Jupyter based on Tone.js

extra:
  recipe-maintainers:
    - benbovy
    - davidbrochart
