{% set name = "ipytone" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34bb7e41af5710cd0308705a455979e4a0ff193fad16815cf4e1f9ba6d2f7ee6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatch-jupyter-builder >=0.8.2
    - hatch-nodejs-version
    - hatchling
    - python >=3.6
    - pip
  run:
    - ipywidgets >=7.6.0,<9
    - python >=3.6
    - numpy
    - traittypes

test:
  requires:
    - pip
    - pytest
    - pytest-mock
    - jupyterlab >=3.1,<4
    - m2-grep  # [win]
  imports:
    - ipytone
  commands:
    - pip check
    # python tests
    - pytest -vv --pyargs ipytone
    # show list of lab extensions for debugging
    - jupyter labextension list
    # check ipytone lab extension valid
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "ipytone.*OK.*ipytone" labextensions
    # show list of classic notebook extensions for debugging
    - jupyter nbextension list
    # check ipytone nbextension files
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipytone/extension.js    # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipytone/index.js        # [unix]

about:
  home: https://github.com/benbovy/ipytone
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Interactive audio in Jupyter based on Tone.js
  doc_url: https://ipytone.readthedocs.io

extra:
  recipe-maintainers:
    - benbovy
    - davidbrochart
